Develop
DmitryjVeselyj/Intelligent-Placer pull request #1
Opened 2022-09-16 22:51 UTC by DmitryjVeselyj

В images находятся все фотографии. Предметы находятся в images/things, а тесты в images/input. Описание тестов(наиболее показательных) и их ожидаемые результаты добавил в .csv файл

2022-10-11 22:08 UTC, lyphrowny reviewed
Отразил в комментариях возможные неточности и/или кажущиеся ошибки

UPD: прошу прощения за комментарии, прыгающие из одного места в файле в другое, -- думал, они будут отсортированы в естественном порядке

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +    <li>Минимальное разрешение 10мп</li>
Как будет проверяться выполнение этого условия?

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +    <li>Освещение комнатное(равномерное и без тёмных областей)</li>
Некоторые предметы отбрасывают тень, т.е. создают темные области

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +    <li>Рисуется на листе тёмным маркером</li>
Имеет ли значение толщина линии? Есть [маркеры с толщиной линии 0.1 мм](https://razmery.info/dom/raznoe/razmery-kancelyarii-markerov.html)

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +    <li>Выпуклый многоугольник</li>
Почти любое размещение в многоугольнике почти любого предмета сделает многоугольник невыпуклым для последующих размещений

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +20.jpg,,0
Отсутствует описание

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +    <li>Объекты не могут перекрывать друг друга</li>
- Могут ли предметы находиться внутри друг друга? Например, монета помещается внутрь ушка ножниц

- Могут ли предметы быть расположены вплотную к друг другу? Существует ли минимальное допустимое расстояние между ними?

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +    <li>Объекты должны находиться снизу листа</li>
Первые 3 пункта списка описывают расположение исходных предметов на листе, поэтому последующие пункты читаются в том же ключе, а, оказывается, эти пункты уже относятся к расположению предметов на совместном фото с многоугольником

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +, если объекты можно поместить в фигуру, иначе False</p>
Вводимые понятия почти сразу же игнорируются и заменяются

- многоугольник -> нарисованная фигура
- предметы -> объекты

Или это-таки разные сущности? Тогда следующий вывод кажется валидным
> По фото предметов с многоугольником программа должна определить, возможно ли размещение предметов в нарисованной фигуре, которая может не быть представленным на фото многоугольником

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +                <li>Если мы знаем, какой и где контур многоугольника, то контурами предметов будут все полученные контуры, за исключением собственно многоугольника</li>
На прошлом шаге контуры как листа, так и многоугольника были найдены, почему бы их не убрать с изображения?

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +            <li>Кроме того, желательно подбирать положения предметов так, чтобы они занимали "логичное" положение(т.е. если у нас многоугольник и предмет прямоугольной формы, то, если представляется
Если "логичное" положение предмета прямоугольной формы подобрать не получается, алгоритм вырождается в полный перебор

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +        <li>Пока кажется <s>неразумной</s> разумной идея перебора(что-то в виде smart перебора) всех возможных вариантов и положений объектов</li>
Даже с улучшениями получается слишком много итераций. Рассмотрим предмет прямоугольной формы

- Угол поворота [0; 90] (в силу симметрии), шаг - 1 градус, тогда количество поворотов -- 90
- Пусть многоугольник есть квадрат 100х100 пикселей, тогда возможных положений предмета 100*100 = 10^4
- Тогда возможных положений для одного предмета: 90 * 10^4 ~ 10^6

---
> перебора ... всех возможных вариантов и положений объектов

То есть на каждое положение объекта приходятся всевозможные положения других предметов? (10^6)^n, где n -- количество других предметов?

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +<li>При этом попытаться уложить первыми самые большие предметы, а затем уже те, которые меньше</li>
По какому критерию сортируются предметы?

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +        <li>Впоследствии использовать некий критерий того, что предметы можно добавить в многоугольник(как вариант площадь оставшейся области)</li>
Что происходит с многоугольником при добавлении в него предмета? У многоугольника просто уменьшается площадь, но сам он при этом не изменяется?

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +                <li>Учитывая требование, при котором объекты должны находиться ниже листа, можно попытаться
Как считать самый верхний контур? Если по первой встреченной линии при движении по фото сверху вниз, то самым верхним контуром будет контур листа, ибо многоугольник не должен выходить за границы листа

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +        <li>Возможно дополнительная обработка(скорее всего, это будут морфологические операции)</li>
Кажется, фильтр Кэнни не даст непрерывных сторон многоугольника. Какие морфологические операции смогут устранить разрыв? Не будет ли многоугольник искажен при этом?

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +        <li>Произвести сопоставление с предметами из тренировочного набора, у которых, скорее всего, так же будут выделены границы(пока наиболее разумными кажутся две идеи)</li>
Поскольку расстояние между предметами не оговорено, один предмет может находиться в тени другого предмета, что должно затруднить обнаружение границы предмета, а следовательно и его сопоставление исходному предмету

2022-10-11 22:08 UTC, lyphrowny commented on README.md
> +                <li>Использовать какую-то метрику для сравнения предметов(как вариант наименьший модуль разности между пикселями края изображения и ближайшего края изображения из тестового набора. За
> пикселями края изображения

Это рамка шириной в 1 пиксель? Как разности между пикселями, которые принадлежат рамкам рассматриваемых изображений, помогут определить сходство объектов?

> ближайшего края изображения

Какой край является ближайшим?

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +13.jpg,����� ��������� � �������������,0
Во вкладке "Измененные файлы" русские символы не отображаются

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +1.jpg,�������� ������������ �� ������� ���������,1
Нарисованная фигура не является многоугольником, ибо не замкнута

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +2.jpg,�������� ������������ �� ������� ���������,0
Черточка внутри многоугольника лишает его выпуклости

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +3.jpg,������������� ������ �����,1
Не многоугольник, ибо не замкнут

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +5.jpg,����� �������� � ������� �������������,1
Многоугольник невыпуклый
Щетка для обуви перспективно искажена

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +6.jpg,����� ������ � �������������� � ����� ��������,0
Щетка для обуви перспективно искажена

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +10.jpg,������� ��������� � ��������� ����������� � �����,1
Многоугольник невыпуклый
Щетка для обуви перспективно искажена

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +11.jpg,��������� � ������������� ������ ���������� ������������,0
Многоугольник невыпуклый
Щетка для обуви перспективно искажена

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +13.jpg,����� ��������� � �������������,0
Не многоугольник, ибо не замкнут

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +17.jpg,,1
Многоугольник не выпуклый
Щетка для обуви перспективно искажена

2022-10-11 22:08 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +20.jpg,,0
Многоугольник невыпуклый

2022-10-15 09:33 UTC, DmitryjVeselyj commented on README.md
> +    <li>Минимальное разрешение 10мп</li>
Это условие на совести фотографирующего, т.е. меня

2022-10-15 09:38 UTC, DmitryjVeselyj commented on README.md
> +    <li>Освещение комнатное(равномерное и без тёмных областей)</li>
Согласен. Но в моих условиях полностью избавиться от теней не представляется возможным. К тому же, как мне кажется, тени не слишком сильно видны, чтобы в дальнейшем как-то критично повлиять на распознавание объектов. Возможно я ошибаюсь, в скором времени это выяснится

2022-10-15 09:46 UTC, DmitryjVeselyj commented on README.md
> +    <li>Рисуется на листе тёмным маркером</li>
Я думаю, что независимо от толщины линии границы объекта всё равно должны нормально распознаваться, так же как и внутренность многоугольника. Подразумевается, что используется обычный стандартный маркер, без каких-либо особенностей типа ультратонкий маркер с невидимыми чернилами

2022-10-15 09:51 UTC, DmitryjVeselyj commented on README.md
> +    <li>Выпуклый многоугольник</li>
Не спорю, но ведь это требования к входным данным, а не к итерациям алгоритма. Кроме того, требование выпуклости многоугольника написано умышленно из-за незнания конкретики работы будущей программы. Т.е. я решил вначале ужесточить требования, а затем, если представится возможным, их ослабить

2022-10-15 10:01 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +20.jpg,,0
Цитата из файла по Intelligent Placer на гугл-диске: "Из всех примеров надо отобрать 10-15 наиболее репрезентативных, для каждого из них написать, чем именно его случай примечателен "

2022-10-15 10:05 UTC, DmitryjVeselyj commented on README.md
> +    <li>Объекты не могут перекрывать друг друга</li>
1) Посколько я сам ещё этого не знаю, то скажу, что нельзя. Потом, может быть, будет можно)
2) Вплотную - нет. Между предметами должно быть такое расстояние, которое не мешало бы их распознаванию

2022-10-15 10:13 UTC, DmitryjVeselyj commented on README.md
> +    <li>Объекты должны находиться снизу листа</li>
Это же список требований к предметам. Каждый из элементов списка выражает какое-то независимое от других требование, которое может быть записано в любом порядке(нет нумерации). Да, в целом, можно выделить подмножество требований, которое назвать "расположение предметов на совместном фото с многоугольником", но , в таком случае, весь README превратится в огромный список списков

2022-10-15 10:22 UTC, DmitryjVeselyj commented on README.md
> +, если объекты можно поместить в фигуру, иначе False</p>
1)Как ни странно, но опять цитата из файла на гугл-диске:" Многоугольник может задаваться 2-мя способами: а) массивом с координатами вершин на естественной плоскости (не в пикселях); б) фигурой, нарисованной темным маркером на белом листе бумаги".
2)Чтобы избежать тавтологии, текст был наполнен словами-синонимами, но, на всякий случай, дабы избежать недопонимания
![image](https://user-images.githubusercontent.com/71879233/195981280-aecd0182-044a-4b8e-9079-145c2e114792.png)

![image](https://user-images.githubusercontent.com/71879233/195981150-fcb6a662-9af3-43a1-9c88-57a498608614.png)

2022-10-15 10:32 UTC, DmitryjVeselyj commented on README.md
> +                <li>Если мы знаем, какой и где контур многоугольника, то контурами предметов будут все полученные контуры, за исключением собственно многоугольника</li>
Имелось в виду, что, когда мы получим изображение, то гарантированно будем знать, что, например, в нижней четверти изображения будут находиться только предметы, а в остальной части лист с многоугольником. Таким образом, мы сразу можем понять и отличить, где будут контуры многоугольника и предметов(может быть имеет смысл как-то попробовать ориентироваться на распознавание контуров листа). С Вашим замечанием я согласен, скорее всего, попробую реализовать такое в алгоритме

2022-10-15 10:35 UTC, DmitryjVeselyj commented on README.md
> +            <li>Кроме того, желательно подбирать положения предметов так, чтобы они занимали "логичное" положение(т.е. если у нас многоугольник и предмет прямоугольной формы, то, если представляется
Честно говоря, прямо хорошего и красивого алгоритма без изъянов я ещё не придумал. При реализации я постараюсь придумать что-то более разумное, дабы не доходить до полного перебора

2022-10-15 10:37 UTC, DmitryjVeselyj commented on README.md
> +        <li>Пока кажется <s>неразумной</s> разумной идея перебора(что-то в виде smart перебора) всех возможных вариантов и положений объектов</li>
Как я уже писал выше(или ниже), идея перебора всех возможных положений мне самому не очень нравится, поэтому в дальнейшем буду генерировать что-то более логичное

2022-10-15 10:38 UTC, DmitryjVeselyj commented on README.md
> +<li>При этом попытаться уложить первыми самые большие предметы, а затем уже те, которые меньше</li>
Скорее всего, сортировка будет по площади

2022-10-15 10:54 UTC, DmitryjVeselyj commented on README.md
> +        <li>Впоследствии использовать некий критерий того, что предметы можно добавить в многоугольник(как вариант площадь оставшейся области)</li>
Изменяется, но пока у меня несколько вариантов на то, как учитывать занятие места в многоугольнике:
- Вырезать каким-нибудь образом занятое пространство
- Заполнять это пространство какими-нибудь пикселями
- Придумаю ещё что-нибудь

2022-10-15 11:07 UTC, DmitryjVeselyj commented on README.md
> +                <li>Учитывая требование, при котором объекты должны находиться ниже листа, можно попытаться
Если идти сверху вниз, то самым верхним контуром будет контур листа. Планируется определить границы листа, а в нём уже будут находиться границы многоугольника. Затем, можно по Вашему совету убрать с изображения лист и многоугольник, тогда все остальные контуры будут контурами предметов. Или, как я писал уже, рассматривать некоторую часть изображения(т.е. в нижней четверти только предметы, а дальше только лист и многоугольник)

2022-10-15 11:12 UTC, DmitryjVeselyj commented on README.md
> +        <li>Возможно дополнительная обработка(скорее всего, это будут морфологические операции)</li>
Честно говоря, сам я точно не уверен, но дилатация должна помочь устранять разрывы. Надеюсь, что искажение, если будет, то оно будет несущественным. Опять же повторюсь, в дальнейшем при возникновении данных проблем будут продумываться способы их решения и дополнение плана с требованиями

2022-10-15 11:14 UTC, DmitryjVeselyj commented on README.md
> +        <li>Произвести сопоставление с предметами из тренировочного набора, у которых, скорее всего, так же будут выделены границы(пока наиболее разумными кажутся две идеи)</li>
Согласен. Планирую дополнить требования, связанные с расстоянием между предметами

2022-10-15 11:20 UTC, ViktorUshkov reviewed
В основном, мой коллега основательно отревьюил вашу работу, поэтому мне было мало что добавить к его комментариям

2022-10-15 11:20 UTC, ViktorUshkov commented on README.md
> +    <li>Число вершин не больше 10</li>
Насколько это критичное требование? Как поведение программы изменится если у многоугольника будет 11 вершин, а не 10?

2022-10-15 11:20 UTC, ViktorUshkov commented on README.md
> +        <li>Имеет смысл добавить обработку каких-то критичных случаев, когда мы можем сразу дать ответ на то, сможем ли мы расположить объекты в многоугольнике(например, сумма площадей объектов > пло
Мне кажется, такую проверку нужно сделать в первую очередь

2022-10-15 11:45 UTC, DmitryjVeselyj commented on README.md
> +                <li>Использовать какую-то метрику для сравнения предметов(как вариант наименьший модуль разности между пикселями края изображения и ближайшего края изображения из тестового набора. За
Касательно идеи про метрику:
1. Допустим, у нас есть предмет в тренировочном наборе, границы которого будут представлять собой что-то вроде треугольника.
2. На тестовом изображении мы найдём контур, который тоже будет похож на треугольник
3. Тогда используя метрику max min|a - b|, a – пиксели края изображения из тренировочного набора, b – пиксели края изображения из тестового изображения. В теории эта метрика при схожих размерах и форме объектов должна быть небольшой величины.

Возможно, эта идея не особо рабочая, главный упор, скорее всего, будет именно на особые точки, а не на метрику.

2022-10-15 11:48 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +13.jpg,����� ��������� � �������������,0
Не знаю, почему тут решили некрасиво отображаться русские символы, поэтому прикладываю скрин, как оно выглядит, если смотреть непосредственно из репозитория, а не из вкладки, где делается ревью 
![image](https://user-images.githubusercontent.com/71879233/195984802-887ca075-2539-42c5-b430-74c2ce62d98d.png)

2022-10-15 11:51 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +1.jpg,�������� ������������ �� ������� ���������,1
Согласен. Возможно преобработка изображений сможет устранить разрывы, хотя, скорее всего, я просто перефотографирую

2022-10-15 11:54 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +2.jpg,�������� ������������ �� ������� ���������,0
Ответ такой же, как к комментарию выше(или ниже). Касательно выпуклости, возможно, это требование даже излишне, но т.к. я решил вначале ужесточить требования, а потом,если получится, ослабить, оно пока остаётся

2022-10-15 11:55 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +3.jpg,������������� ������ �����,1
Согласен. Возможно преобработка изображений сможет устранить разрывы, хотя, скорее всего, я просто перефотографирую

2022-10-15 11:57 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +5.jpg,����� �������� � ������� �������������,1
Согласен. Скорее всего, просто перефотографирую

2022-10-15 11:57 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +6.jpg,����� ������ � �������������� � ����� ��������,0
Согласен. Скорее всего, просто перефотографирую

2022-10-15 11:57 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +10.jpg,������� ��������� � ��������� ����������� � �����,1
Согласен. Скорее всего, просто перефотографирую

2022-10-15 11:57 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +11.jpg,��������� � ������������� ������ ���������� ������������,0
Согласен. Скорее всего, просто перефотографирую

2022-10-15 11:57 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +13.jpg,����� ��������� � �������������,0
Согласен. Скорее всего, просто перефотографирую

2022-10-15 11:57 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +17.jpg,,1
Согласен. Скорее всего, просто перефотографирую

2022-10-15 11:58 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +20.jpg,,0
Согласен. Скорее всего, просто перефотографирую

2022-10-15 12:00 UTC, DmitryjVeselyj commented on README.md
> +    <li>Число вершин не больше 10</li>
Честно говоря, это требование написано из-за незнания будущей работы программы. Вероятнее всего, важно лишь то, чтобы вершины были различимы, поэтому наверняка в дальнейшем требования будут изменены

2022-10-15 12:00 UTC, DmitryjVeselyj commented on README.md
> +        <li>Имеет смысл добавить обработку каких-то критичных случаев, когда мы можем сразу дать ответ на то, сможем ли мы расположить объекты в многоугольнике(например, сумма площадей объектов > пло
Именно так и будет сделано, иначе проверка в конце алгоритма не имела бы никакого смысла

2022-10-15 15:33 UTC, lyphrowny commented on images/input/ExpectedResultsWithDescr.csv
> +13.jpg,����� ��������� � �������������,0
Спасибо!
Возможно, стоит добавить такие особые случаи
* нет листа с многоугольником, есть предметы
* есть лист с многоугольником, нет предметов
* нет ни листа с многоугольником, ни предметов
* есть пустой лист, нет предметов
* есть пустой лист, есть предметы
* есть лист с ломаной (не многоугольник), нет предметов
* есть лист с ломаной (не многоугольник), есть предметы

2022-10-15 16:02 UTC, lyphrowny commented on README.md
> +                <li>Использовать какую-то метрику для сравнения предметов(как вариант наименьший модуль разности между пикселями края изображения и ближайшего края изображения из тестового набора. За
"пиксели края изображения" == пиксели края границ \ контура предмета?
Мне кажется, идея с метрикой неплоха, но она может давать некорректный результат. 
Рассмотрим три контура: a - все пиксели (0, 0, 0), b - (50, 50, 50), c - (100, 100, 100), тогда метрика(a, b) = метрика(b, c) -> a = c, что неверно

2022-10-15 16:13 UTC, DmitryjVeselyj commented on images/input/ExpectedResultsWithDescr.csv
> +13.jpg,����� ��������� � �������������,0
Спасибо, в дальнейшем постараюсь добавить

2022-10-15 16:17 UTC, DmitryjVeselyj commented on README.md
> +                <li>Использовать какую-то метрику для сравнения предметов(как вариант наименьший модуль разности между пикселями края изображения и ближайшего края изображения из тестового набора. За
1) "пиксели края изображения" == пиксели края границ \ контура предмета? - Если я Вас правильно понял, то да.
2) В случае равенства по сути будет получаться, что на совпадение с объектом будут два кандидата. Тогда, как вариант, можно провести какую-то дополнительную обработку или же просто выбрать один из них

2022-10-15 16:44 UTC, lyphrowny commented on README.md
> +    <li>Объекты должны находиться снизу листа</li>
> Каждый из элементов списка выражает какое-то независимое от других требование

Но тогда требования взаимоисключающие
* Объекты должны находиться снизу листа
* Объект не выходит за границы листа

> можно выделить подмножество требований

Можно избежать этого, добавив, например, контекст: "предмет на исходных данных" и "предмет на тестовых данных"

2022-10-15 17:54 UTC, DmitryjVeselyj commented on README.md
> +    <li>Объекты должны находиться снизу листа</li>
Да, спасибо, исправлю.
Действительно, тут имелось в виду, что объекты на тестовых данных находятся снизу листа, а на исходных данных не выходят за границу листа.

2022-10-15 18:08 UTC, lyphrowny commented on README.md
> +, если объекты можно поместить в фигуру, иначе False</p>
"Эверест -- высочайшая вершина Земли. Джомолунгма располагается в Китае" -- очевидно ли, что Эверест и Джомолунгма является названием одной и той же вершины? Нет, если об этом не знать. Ничто не мешает возможному пользователю не знать, что "многоугольник" и "фигура" есть то же самое. Мне кажется, что точность понятий важнее избегания тавтологии

Вернемся к постановке
> по фотографиям предметов на светлой поверхности и многоугольнику выдавать результат о том, можно ли расположить данные предметы так, чтобы они влезли в нарисованную фигуру

- "расположить данные предметы так, чтобы они влезли" -- расположить каждый по отдельности? все вместе? возможны ли пересечения предметов при их расположении внутри? (частичные ответы на эти вопросы есть в комментариях, но нет ни в требованиях, ни в плане)
- "предметов ... многоугольнику ... нарисованную фигуру" -- здесь ничто не мешает использовать два различных многоугольника: один на фото с предметами (ответ для которого True), другой, допустим, на бумажке в руке (ответ для которого False); и говорить, что программа работает неверно

Мне кажется, стоит запретить такие толкования постановки задачи именно в постановке, а не в требованиях \ плане

2022-10-15 21:16 UTC, DmitryjVeselyj commented on README.md
> +, если объекты можно поместить в фигуру, иначе False</p>
Если пользователь не знает значения слов "многоугольник" и "фигура", то как он может вообще в целом читать текст на русском языке, ведь это базовый лексикон. В таком случае, любое сочетание слов будет вызывать у него двусмысленность и недопонимание.

Касательно предложения "расположить данные предметы так, чтобы они влезли". По той же логике могут возникнуть вопросы, какие "данные предметы", что подразумевается под словом "предметы",  что за "они" и т.д. Любое слово можно подвергнуть сомнению и в итоге никакое предложение не получится написать так, чтобы его поняли другие люди. Кроме того, необходимо будет добавлять к каждому слову пояснения, в каком контексте они используются, что увеличит объём текста, приведёт к избытку информации и ровно так же может быть неправильно интерпретированно. Как пример, "данные предметы, которые находятся на фотографии должны целиком расположиться в многоугольнике". Сразу можно придумать такие вопросы:
-  на какой фотографии?На той, что сфотографировали или расположенной на сайте Политеха,
-  расположиться под каким углом? Под тем же, что на фотографии(какой фотографии?) или в результате какого-то преобразования, или может вообще они могут стать искажёнными?
Да, необходимы уточнения о расположении предметов, могут ли они пересекаться, накладываться друг на друга 
и т.д. Но все эти уточнения должны быть в разумных рамках.

"предметов ... многоугольнику ... нарисованную фигуру" - здесь та же история, что я написал выше. Допустим, вместо "нарисованную фигуру" я использовал бы "многоугольник". Можно задать те же вопросы:
- одни и те же ли многоугольники?
- что вообще такое многоугольник?В моём понимании многоугольник - это фигура, а в понимании других это может быть что-то другое.

Если смотреть предложение дальше, то использовано первым слово "многоугольник", а затем уже "нарисованная фигура", что явно указывает на расширение понятия, а не введение какого-либо другого. 

В случае запрета таких толкований, мне кажется,что даже при условии использования одного слова на весь текст, даже если я напишу перед этим определения и их синонимы, всё равно можно будет придумать вопросы и истолковать любое предложение в совершенно любом смысле.

2022-10-23 08:59 UTC, ThinkingFrog requested changes

2022-10-23 08:59 UTC, ThinkingFrog commented on .idea/Intelligent-Placer.iml
> +  <component name="PyDocumentationSettings">
Обычно всю директорию .idea добавляют в .gitignore, это в основном не переносимые user specific файлы, которые ломают проект при работе нескольких людей над ним

2022-10-23 08:59 UTC, ThinkingFrog commented on README.md
> +<h1>Intelligent Placer</h1>
Насколько я помню, идеологически markdown не приветствует использование html-разметки там, где справляется md-разметка. Но это в общем-то дело вкуса по большей части

2022-10-23 08:59 UTC, ThinkingFrog commented on README.md
> +    <li>Объекты должны находиться снизу листа(на тестовых данных)</li>
Лучше написать в нижней части (половине, например). Отсюда не очевидно, что они должны находиться в границах листа, а не под ним. Это вытекает из пунктов выше, но конкретно этот пункт может запутать

2022-10-23 08:59 UTC, ThinkingFrog commented on README.md
> +    <li>Формат ".jpg"</li>
jpg и jpeg это, насколько я помню, один и тот же формат. Если указывается расширение файла, то лучше указать оба

2022-10-23 08:59 UTC, ThinkingFrog commented on intelligent_placer_lib/algorithm.py
> +import cv2
Не могу откомментить в нужной директории, поэтому пишу здесь. \_\_pycache\_\_/ однозначно нужно добавить в .gitignore, это бинарные файлы, которые нужны только интерпретатору питона и легко создаются и хранятся в локальной копии репозитория. В удаленном репозитории они не нужны и даже вредны, так как при каждом коммите они будут полностью изменяться и каждое изменение будет храниться в истории репозитория, со временем репозиторий будет неоправданно расти в размере

2022-10-23 08:59 UTC, ThinkingFrog commented on intelligent_placer_lib/algorithm.py
> +def the_best_algorithm_in_the_world(polygon, things):
Здесь и дальше по коду сильно не хватает тайп хинтов для параметров функций и возвращаемых значений. С ними будет проще читать и поддерживать код

2022-10-23 09:20 UTC, DmitryjVeselyj commented on .idea/Intelligent-Placer.iml
> +  <component name="PyDocumentationSettings">
Как раз вчера пытался добавить .gitignore. Даже вручную удалил директории из репозитория,но когда пытался запушить изменения, вылетала ошибка о том,что репозитории не синхронизированы. Делал git pull и выдавало "already up to date". Мои эксперименты можно увидеть как раз по примерно последним пяти коммитам. В последующем проблему постараюсь решить и лишних файлов не будет

2022-10-23 09:21 UTC, DmitryjVeselyj commented on README.md
> +    <li>Объекты должны находиться снизу листа(на тестовых данных)</li>
Немного эта деталь описана в плане, но, в целом, согласен

2022-10-23 09:21 UTC, DmitryjVeselyj commented on README.md
> +<h1>Intelligent Placer</h1>
Это тоже мои эксперименты были)

2022-10-23 09:22 UTC, DmitryjVeselyj commented on intelligent_placer_lib/algorithm.py
> +import cv2
Написал выше про .gitignore

2022-10-23 09:22 UTC, DmitryjVeselyj commented on intelligent_placer_lib/algorithm.py
> +def the_best_algorithm_in_the_world(polygon, things):
В будущем постараюсь добавить

2022-10-23 09:39 UTC, DmitryjVeselyj commented on README.md
> +    <li>Формат ".jpg"</li>
Хорошо

2022-10-23 16:51 UTC, ThinkingFrog commented on .idea/Intelligent-Placer.iml
> +  <component name="PyDocumentationSettings">
Сильно не разбирался в коммитах, но генерально если есть проблемы с рассинхроном удаленного и локального репозитория, то имеет смысл:

1. Сделать `git stash`, если не все локальные изменения закоммичены, то есть `git status` выдает изменение файлов по сравнению с локальным деревом гита. Ну или закоммитить изменения через `git commit`
2. Спуллить изменения `git pull --no-ff`
3. Если появятся конфликты после пулла, то руками их решить
4. Когда удалённый и локальный репозиторий смержены, сделать `git push`, если есть локальные коммиты, ещё не отправленные на ремоут
5, Удалить лишние директории, закоммитить
6. Добавить удалённые директории в корневой гитигнор и закоммитить его отдельно от п.5

Если вылезает up to date, то возможно стоит сделать `git fetch` или проверить, что в `git config -l` указаны нужный ремоут, ветка и всё остальное

2022-10-23 17:21 UTC, DmitryjVeselyj commented on .idea/Intelligent-Placer.iml
> +  <component name="PyDocumentationSettings">
Рассинхрон как раз появлялся из-за того, что я папки удалял прямиком на гитхабе. Может быть я фигню какую-то делал, но я предполагал, что если произойдут какие-то изменения, то после git pull я как раз эти изменения себе загружу на локальный репозиторий. Почему этого не происходило, я так и не понял. Возможно действительно надо было просто руками попробовать решить(хотел даже попробовать залить через git push --force, но подумал, что так делать не стоит). Проблему сейчас решил просто клонированием репозитория и удалением папок вначале на локальном репозитории и добавлением .gitignore

P.S. За советы спасибо)

2022-10-23 18:23 UTC, ThinkingFrog commented on .idea/Intelligent-Placer.iml
> +  <component name="PyDocumentationSettings">
Прямиком на гитхабе лучше вообще ничего не делать, работать с локальной копией репозитория и через команды гита синкать локальный с ремоутом. `git push --force` правда лучше использовать только в совсем специфичных случаях. Но что получилось решить проблему это в любом случае хорошо)

2022-10-23 18:26 UTC, ThinkingFrog approved these changes

2022-10-25 11:23 UTC, IvAlexsay reviewed
Оказывается забыл закончить ревью(

2022-10-25 11:23 UTC, IvAlexsay commented on README.md
> +    <li>Угол между перпендикуляром к поверхности и направлением камеры < 5 градусов</li>
Добавлю, относительно комментария ниже, касающегося разрешения камеры, что проверять угол и высоту тоже кажется невозможным.

2022-10-25 11:23 UTC, IvAlexsay commented on README.md
> +        <li>Размеры предметов, как и размер многоугольника, планируется находить с опорой на то, что мы используем лист А4, а его размеры известны заранее</li>
А разве размеры предметов неизвестны заранее?

2022-10-27 15:32 UTC, lyphrowny reviewed
Красивое оформление demonstration.ipynb. Было не очень удобно сравнивать исходное изображение с разделенными изображениями \ изображениями с контурами, возможно, стоит выводить их вместе

Логически чистый код: очень приятно читать! Может быть, стоит добавить комментарии к шапкам функций и \ или к телу функции, но пока было все достаточно понятно

Другие комментарии \ замечания оставил в in-place комментариях

2022-10-27 15:32 UTC, lyphrowny commented on README.md
> +    <li>Фон светлый</li>
Должен ли фон быть равномерным? Например, без вкраплений, других артефактов поверхности

2022-10-27 15:32 UTC, lyphrowny commented on README.md
> +<h3>Фигура</h3>
Стоит требовать единственность многоугольника на листе
Возможна ли полная закраска многоугольника? Частичная, если убрать требование выпуклости?

2022-10-27 15:32 UTC, lyphrowny commented on README.md
> +        <li>Размеры предметов, как и размер многоугольника, планируется находить с опорой на то, что мы используем лист А4, а его размеры известны заранее</li>
Зачем находить размеры предметов? Не будет ли достаточно маски и ее атрибутов, чтобы сопоставить предметы исходным данным?

2022-10-27 15:32 UTC, lyphrowny commented on README.md
> +        <li>Произвести сопоставление с предметами из тренировочного набора, у которых, скорее всего, так же будут выделены границы(пока наиболее разумными кажутся две идеи)</li>
Зачем производить сопоставление предметам исходных данных? Чтобы не рассматривать предметы, не представленные в исходных данных?

2022-10-27 15:32 UTC, lyphrowny commented on README.md
> +<h3>Предметы</h3>
Могут ли предметы (и на тестовых, и на исходных данных) повторяться?

2022-10-27 15:32 UTC, lyphrowny commented on README.md
> +                <li>Для каждого объекта найти особые точки и проводить сравнение уже по ним</li>
Скорее всего это не сработает для небольших предметов (монета): не находятся особые точки (личный опыт, пуговица)

2022-10-27 15:32 UTC, lyphrowny commented on intelligent_placer_lib/algorithm.py
> +    return choice([False, True])
Понятно, что функция несерьезная, но лучше заменить рандом в ответе на нейтральное значение, например, `None`. Это позволит избежать false positives, а также даст понимание, учлись ли какие-либо условия

2022-10-27 15:32 UTC, lyphrowny commented on intelligent_placer_lib/loading.py
> +        if filename.endswith('.jpg'):
Следует добавить ".jpeg"

2022-10-27 15:32 UTC, lyphrowny commented on intelligent_placer_lib/loading.py
> +    if images_path.endswith('jpg'):
Следует добавить ".jpeg"

2022-10-27 15:32 UTC, lyphrowny commented on intelligent_placer_lib/algorithm.py
> +    if cv2.contourArea(polygon) < sum([cv2.contourArea(obj) for obj in things]):
Можно добавить сравнение по максимальной из площадей предметов

2022-10-27 15:32 UTC, lyphrowny commented on intelligent_placer_lib/intelligent_placer.py
> +    min_width, max_width = 0, 800
Значения могут стать невалидными при изображении большего разрешения, например, 3000х4000 px

2022-10-27 15:32 UTC, lyphrowny commented on intelligent_placer_lib/intelligent_placer.py
> +    things_contours = get_things_contours(things_image)
Возможно, стоит добавить какую-то фильтрацию контуров: площадь, размеры bbox и др.

2022-10-27 15:32 UTC, lyphrowny commented on intelligent_placer_lib/preprocessing.py
> +    return img
Кажется, решение подходит для небольшого множества входных данных из-за подбора констант в фильтре Кэнни: работает на тех данных, на которых создавалось, но будет ли работать на других данных, удовлетворяющих требованиям?

2022-10-27 15:32 UTC, lyphrowny commented on intelligent_placer_lib/recognizing.py
> +    max_area_contour = max(contours, key=lambda x: cv2.contourArea(x))
Стоит проверить, что максимальный контур -- не контур листа

2022-10-27 15:32 UTC, lyphrowny commented on README.md
> +<h2>Требования</h2>
Стоит добавить, что алгоритм может работать некорректно на данных, не удовлетворяющих требованиям. Тогда можно будет "игнорировать" труднопроверяемые требования

2022-10-27 15:32 UTC, lyphrowny commented on README.md
> +        <li>Возможно дополнительная обработка(скорее всего, это будут морфологические операции)</li>
Наверно, стоит добавить используемые в алгоритме морфологические операции

2022-10-27 19:21 UTC, DmitryjVeselyj commented on README.md
> +        <li>Размеры предметов, как и размер многоугольника, планируется находить с опорой на то, что мы используем лист А4, а его размеры известны заранее</li>
Например, если бы предметы были на одном листе, а на другом многоугольник, то как раз пришлось бы находить "истинный" размер предметов и многоугольника, чтобы всё было в одном масштабе

2022-10-27 19:24 UTC, DmitryjVeselyj commented on README.md
> +    <li>Фон светлый</li>
Я бы сказал, что лучше, конечно, равномерный фон. Но даже у меня на тестовых фотографиях есть небольшие точки. Пока что сильного влияния они не оказали и, надеюсь, не окажут

2022-10-27 19:25 UTC, DmitryjVeselyj commented on README.md
> +<h3>Фигура</h3>
Думаю, что частичная и полная закраска возможны, но прямо точно сказать на данный момент не могу(хотя cv2.findContours вроде нормально внешние контуры ищет)

2022-10-27 19:26 UTC, DmitryjVeselyj commented on README.md
> +        <li>Размеры предметов, как и размер многоугольника, планируется находить с опорой на то, что мы используем лист А4, а его размеры известны заранее</li>
Честно говоря, сам не знаю)
Сейчас кажется, что размеры не особо обязательны, но потом всё может поменяться

2022-10-27 19:32 UTC, DmitryjVeselyj commented on README.md
> +        <li>Произвести сопоставление с предметами из тренировочного набора, у которых, скорее всего, так же будут выделены границы(пока наиболее разумными кажутся две идеи)</li>
В принципе, ответ такой же, как на комментарий выше. 
Есть идея, что это может помочь при различных перспективных искажениях,дабы узнать реальный контур неискажённого предмета,  хотя в требованиях +- ограничение на минимизацию этого эффекта есть(угол наклона камеры)

2022-10-27 19:32 UTC, DmitryjVeselyj commented on README.md
> +<h3>Предметы</h3>
В требованиях этот момент упоминался(нет, не могут)

2022-10-27 19:33 UTC, DmitryjVeselyj commented on README.md
> +                <li>Для каждого объекта найти особые точки и проводить сравнение уже по ним</li>
Тогда попробуем метрику или ещё что-нибудь, что придёт в голову

2022-10-27 19:33 UTC, DmitryjVeselyj commented on intelligent_placer_lib/algorithm.py
> +    return choice([False, True])
Согласен, но, как Вы уже и сказали, функция несерьёзная

2022-10-27 19:33 UTC, DmitryjVeselyj commented on intelligent_placer_lib/loading.py
> +        if filename.endswith('.jpg'):
Да, спасибо

2022-10-27 19:34 UTC, DmitryjVeselyj commented on intelligent_placer_lib/loading.py
> +    if images_path.endswith('jpg'):
Да, спасибо

2022-10-27 19:37 UTC, DmitryjVeselyj commented on intelligent_placer_lib/algorithm.py
> +    if cv2.contourArea(polygon) < sum([cv2.contourArea(obj) for obj in things]):
Да, но, в целом, сумма и этот случай тоже учитывает

2022-10-27 19:38 UTC, DmitryjVeselyj commented on intelligent_placer_lib/intelligent_placer.py
> +    min_width, max_width = 0, 800
Согласен

2022-10-27 19:38 UTC, DmitryjVeselyj commented on intelligent_placer_lib/intelligent_placer.py
> +    things_contours = get_things_contours(things_image)
Скорее всего, что-нибудь добавлю

2022-10-27 19:40 UTC, DmitryjVeselyj commented on intelligent_placer_lib/preprocessing.py
> +    return img
Тут момент пока в процессе разработки. Понятно, что универсальный алгоритм, который бы идеально работал на любых изображениях, непросто придумать, но какое-то усреднение или что-нибудь в этом роде я попробую реализовать

2022-10-27 19:42 UTC, DmitryjVeselyj commented on intelligent_placer_lib/recognizing.py
> +    max_area_contour = max(contours, key=lambda x: cv2.contourArea(x))
Вообще, на данный момент предобработкой я добился того, что контуры листа полностью пропадают. Однако этот момент тоже хорошо было бы продумать детальнее, потому что на других изображениях полного исчезновения контуров листа может и не быть

2022-10-27 19:44 UTC, DmitryjVeselyj commented on README.md
> +<h2>Требования</h2>
В целом, это, наверное и так понятно, на то они и требования. Возможно, в будущем добавлю

2022-10-27 19:44 UTC, DmitryjVeselyj commented on README.md
> +        <li>Возможно дополнительная обработка(скорее всего, это будут морфологические операции)</li>
Согласен, это имеет смысл

2022-10-28 11:47 UTC, lyphrowny commented on README.md
> +    <li>Фон светлый</li>
Если планируется поддерживать неравномерный фон, стоит добавить пример с таким фоном, иначе добавить равномерность к требованиям

2022-10-28 11:52 UTC, lyphrowny commented on README.md
> +<h3>Фигура</h3>
Если закраска возможна, стоит добавить пример с закраской, иначе потребовать незакрашенность. То же с неединственностью многоугольника: поддерживается - пример, нет - требование

2022-10-28 12:01 UTC, DmitryjVeselyj commented on README.md
> +    <li>Фон светлый</li>
Хорошо

2022-10-28 12:01 UTC, DmitryjVeselyj commented on README.md
> +<h3>Фигура</h3>
Хорошо

2022-10-28 17:41 UTC, ViktorUshkov reviewed
Провел ревью первой итерации: по сути критических замечаний нет, хочу отметить грамотное оформление jupyter-ноутбука.

2022-10-28 17:41 UTC, ViktorUshkov commented on intelligent_placer_lib/loading.py
> +def load_images_from_folder(images_path):
Наличие двух функций, по сути, выполняющих одну работу, кажется избыточным: не лучше ли оставить какой-нибудь один и зарегламентировать стандарт подачи фотографии программе?

2022-10-29 14:06 UTC, DmitryjVeselyj commented on intelligent_placer_lib/loading.py
> +def load_images_from_folder(images_path):
По условию вроде всегда подаётся путь до картинки. Я просто для удобства загрузки тестовых картинок решил добавить эту функцию,хотя можно аналогичную вещь через цикл написать

2022-11-12 19:41 UTC, merged